## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [1]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [2]:
# Type your solution here
import pandas as pd
df = pd.DataFrame.from_dict(data)
df_q12 = df[((df["job"] == "psychologist") | (df["job"] == 'teacher')) & (df["num_cars"] > df["family_size"])]
df_q13 = df[(df["family_size"] <= 2)&(df["num_cars"] >= 1)]
df_q14 = len(set(df["job"]))

print(df_q12)
print(" \n")
print(df_q13)
print(" \n")
print(df_q14)

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
 

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
 

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [3]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [4]:
# Type your solution here
# Type your solution here
df_q2 = pd. concat([fruit, weights], keys = ["fruit", "weights"],axis=1)
df_q2_mean = df_q2.groupby(df_q2["fruit"], axis=0).mean()
print(df_q2_mean)

        weights
fruit          
apple      3.60
banana     6.00
carrot     7.75


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [5]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [6]:
# Type your solution here
# Type your solution here
dict_q3 = {}
list_q3 = []
counter = 0
while counter < len(course_name) :
  dict_q3[course_name[counter]] = counter
  counter += 1

#print("Here is my new function: ", np.argsort(course_name))

sorted_course_name = sorted(dict_q3.items())
for element in sorted_course_name:
  list_q3.append(element[1])

print("This is the list of  the indices of the sorted elements of course_name array: ", list_q3)
print("The result of whether each element of course_name array starts with ""P"" is:", np.char.startswith(course_name, 'P'))  

This is the list of  the indices of the sorted elements of course_name array:  [1, 3, 0, 2, 4]
The result of whether each element of course_name array starts with P is: [ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [7]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [8]:
# Type your solution 

reversed_arr_q4 = student_id[::-1]
print("This is the original array:", student_id)
print("This is the reversed array:", reversed_arr_q4)
print("This is the three largest value: ",sorted(student_id, reverse = True)[0:3])

This is the original array: [1023 5202 6230 1671 1682 5241 4532]
This is the reversed array: [4532 5241 1682 1671 6230 5202 1023]
This is the three largest value:  [6230, 5241, 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [9]:
# Type your solution here
arr =  np.arange(100)
arr = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(sum(arr))


2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [10]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
import numpy as np
# Write a code to swap column 1 with column 2.
arr1 = np.arange(12).reshape(3,4)
arr1[:,[1, 2]] = arr1[:,[2, 1]]
print(arr1)
print(" \n")
arr1[[0,1],:] = arr1[[1,0],:]
print(arr1)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
 

[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
